from setuptools import setup, find_packages

setup(name='django-competition',
      version='0.2.1',
      url='http://github.com/michaelwisely/django-competition',
      license='BSD',
      description='A reusable Django app for hosting various competitions',
      author='Michael Wisely',
      packages=find_packages('src'),
      package_dir={'': 'src'},
      install_requires=['setuptools',
                        'django>1.6,<1.7',
                        'PyYAML==3.10',
                        'factory_boy==2.3.1',
                        'django-guardian==1.1.1',
                        'django-crispy-forms==1.4.0',
                        'djangorestframework==2.3.12',
                        'South==0.8.4',
                        'qrcode==4.0.4',
                        ],
      )
