from setuptools import setup, find_packages

setup(name='django-competition',
      version='0.2.1',
      url='http://github.com/michaelwisely/django-competition',
      license='BSD',
      description='A reusable Django app for hosting various competitions',
      author='Michael Wisely',
      packages=find_packages('src'),
      package_dir={'': 'src'},
      install_requires=['setuptools',
                        'django>1.6,<1.7',
                        'PyYAML==3.11',
                        'factory_boy==2.4.1',
                        'django-guardian==1.2.5',
                        'django-crispy-forms==1.4.0',
                        'djangorestframework==3.1.0',
                        'South==1.0.2',
                        'qrcode==5.1',
                        ],
      )
